apiVersion: apps/v1
kind: Deployment
metadata:
  name: grg-db-psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grg-db-psql
  template:
    metadata:
      labels:
        app: grg-db-psql
    spec:
      containers:
      - name: grg-db-psql
        image: gnuvinicius/grg-db-psql:15.5
        resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432