server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: auth-api
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${AUTH_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWD}
  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${AUTH_DATABASE}
    password: ${POSTGRES_PASSWD}
    user: ${POSTGRES_USER}
    schemas:
    - public
    locations:
    - classpath:db/migration

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /auth/api/v1/swagger
  api-docs:
    path: /auth/v3/api-docs/swagger-config

eureka:
  instance:
    hostname: auth-api
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka
