name: "[PRD] Auth-api project"

on:
  push:
    tags:
      - 1.**

jobs:
  maven_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          architecture: x64
      
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      
      - name: Set version package
        working-directory: ./auth-api
        run: |
          mvn versions:set -DnewVersion=${{steps.branch_name.outputs.SOURCE_TAG}}
          mvn -DskipTests clean package
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: auth-api
          path: ./auth-api/target/auth-api-${{ steps.branch_name.outputs.SOURCE_TAG }}.jar

  push_to_registry:
    needs: maven_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: auth-api
      
      - name: Build and push Docker image
        working-directory: ./auth-api
        run: |
          cp -av auth-api-${{ steps.branch_name.outputs.SOURCE_TAG }}.jar ./auth-api/
          docker build --build-arg APP_NAME=auth-api-${{ steps.branch_name.outputs.SOURCE_TAG }} --tag ${{ vars.DOCKERHUB_USERNAME }}/auth-api:${{ steps.branch_name.outputs.SOURCE_TAG }} .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ vars.DOCKERHUB_USERNAME }}/auth-api:${{ steps.branch_name.outputs.SOURCE_TAG }}
