name: "[HML] web-app project"

on:
  push:
    branches: 
      - "develop"
  workflow_dispatch: 

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Build and push Docker image
        working-directory: ./webapp
        run: |
          docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/webapp:staging .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/webapp:staging

  dev-deploy:
    needs: push_to_registry
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Set kubeconfig file
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Save Nginx Ingress Controller IP as a GITHUB Environment Variable
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV

      - name: Replace token in manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["webapp/k8s/*.yaml"]'
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:staging
          INGRESS_IP: ${{ env.INGRESS_IP }}
      
      - name: Deploy in Development Environment
        run: |
          kubectl apply -f webapp/k8s/deployment.yaml
          kubectl apply -f webapp/k8s/service.yaml
          kubectl apply -f webapp/k8s/ingress.yaml
